spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1632846188@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: dbptkptdexdwbaea
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

spring.jackson.time-zone: Asia/Shanghai

mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml


server:
  port: 8081


