spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

spring.jackson.time-zone: Asia/Shanghai

mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml


server:
  port: 8081